/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 10 19:01:17 GMT 2019
 */

package hu.oe.nik.szfmv.visualization;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import hu.oe.nik.szfmv.automatedcar.bus.packets.input.ReadOnlyInputPacket;
import hu.oe.nik.szfmv.visualization.Dashboard;
import java.awt.image.BufferedImage;
import javax.swing.DebugGraphics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import sun.java2d.SunGraphics2D;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Dashboard_ESTest extends Dashboard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Dashboard dashboard0 = new Dashboard();
      ReadOnlyInputPacket readOnlyInputPacket0 = mock(ReadOnlyInputPacket.class, new ViolatedAssumptionAnswer());
      doReturn(1421).when(readOnlyInputPacket0).getBreakPedalPosition();
      doReturn(1421).when(readOnlyInputPacket0).getGasPedalPosition();
      BufferedImage bufferedImage0 = new BufferedImage(1421, 1421, 1);
      SunGraphics2D sunGraphics2D0 = (SunGraphics2D)bufferedImage0.createGraphics();
      dashboard0.updateDisplayedValues(readOnlyInputPacket0);
      dashboard0.paintComponent(sunGraphics2D0);
      assertEquals(0, sunGraphics2D0.paintState);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Dashboard dashboard0 = new Dashboard();
      // Undeclared exception!
      try { 
        dashboard0.updateDisplayedValues((ReadOnlyInputPacket) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("hu.oe.nik.szfmv.visualization.Dashboard", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Dashboard dashboard0 = new Dashboard();
      DebugGraphics debugGraphics0 = new DebugGraphics();
      // Undeclared exception!
      try { 
        dashboard0.paintComponent(debugGraphics0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
