/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 10 03:54:24 GMT 2019
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.buffer.BigEndianHeapChannelBuffer;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.DirectChannelBufferFactory;
import org.jboss.netty.channel.Channel;
import org.jboss.netty.channel.ChannelHandlerContext;
import org.jboss.netty.channel.DefaultChannelPipeline;
import org.jboss.netty.channel.local.DefaultLocalServerChannelFactory;
import org.jboss.netty.channel.local.LocalServerChannel;
import org.junit.runner.RunWith;
import org.traccar.protocol.TmgFrameDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TmgFrameDecoder_ESTest extends TmgFrameDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TmgFrameDecoder tmgFrameDecoder0 = new TmgFrameDecoder();
      DirectChannelBufferFactory directChannelBufferFactory0 = new DirectChannelBufferFactory();
      byte[] byteArray0 = new byte[9];
      byteArray0[4] = (byte)36;
      BigEndianHeapChannelBuffer bigEndianHeapChannelBuffer0 = new BigEndianHeapChannelBuffer(byteArray0);
      ByteBuffer byteBuffer0 = bigEndianHeapChannelBuffer0.toByteBuffer();
      ChannelBuffer channelBuffer0 = directChannelBufferFactory0.getBuffer(byteBuffer0);
      tmgFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, channelBuffer0);
      assertEquals(9, channelBuffer0.readableBytes());
      assertEquals(0, channelBuffer0.readerIndex());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TmgFrameDecoder tmgFrameDecoder0 = new TmgFrameDecoder();
      byte[] byteArray0 = new byte[8];
      byteArray0[3] = (byte)72;
      BigEndianHeapChannelBuffer bigEndianHeapChannelBuffer0 = new BigEndianHeapChannelBuffer(byteArray0);
      Object object0 = tmgFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, bigEndianHeapChannelBuffer0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TmgFrameDecoder tmgFrameDecoder0 = new TmgFrameDecoder();
      DefaultLocalServerChannelFactory defaultLocalServerChannelFactory0 = new DefaultLocalServerChannelFactory();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      LocalServerChannel localServerChannel0 = defaultLocalServerChannelFactory0.newChannel(defaultChannelPipeline0);
      try { 
        tmgFrameDecoder0.decode((ChannelHandlerContext) null, localServerChannel0, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.TmgFrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TmgFrameDecoder tmgFrameDecoder0 = new TmgFrameDecoder();
      DirectChannelBufferFactory directChannelBufferFactory0 = new DirectChannelBufferFactory();
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte)36;
      BigEndianHeapChannelBuffer bigEndianHeapChannelBuffer0 = new BigEndianHeapChannelBuffer(byteArray0);
      ByteBuffer byteBuffer0 = bigEndianHeapChannelBuffer0.toByteBuffer();
      ChannelBuffer channelBuffer0 = directChannelBufferFactory0.getBuffer(byteBuffer0);
      tmgFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, channelBuffer0);
      assertEquals(0, channelBuffer0.readerIndex());
      assertEquals(9, channelBuffer0.readableBytes());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TmgFrameDecoder tmgFrameDecoder0 = new TmgFrameDecoder();
      byte[] byteArray0 = new byte[8];
      byteArray0[4] = (byte)36;
      BigEndianHeapChannelBuffer bigEndianHeapChannelBuffer0 = new BigEndianHeapChannelBuffer(byteArray0);
      Object object0 = tmgFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, bigEndianHeapChannelBuffer0);
      assertNull(object0);
  }
}
