/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 10 14:30:15 GMT 2019
 */

package org.joo.libra.pointer;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class VariablePredicate_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.joo.libra.pointer.VariablePredicate"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "ANSI_X3.4-1968"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/wasp/Desktop/research/Evosuite/tests/Bears-210/3"); 
    java.lang.System.setProperty("user.home", "/home/wasp"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "wasp"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(VariablePredicate_ESTest_scaffolding.class.getClassLoader() ,
      "org.joo.libra.common.BinaryPredicate",
      "org.joo.libra.common.SimpleHasValue",
      "org.joo.libra.numeric.GreaterEqualPredicate",
      "org.joo.libra.PredicateContext",
      "org.joo.libra.logic.EqualsPredicate",
      "org.joo.libra.numeric.LessEqualPredicate",
      "org.joo.libra.support.PredicateExecutionException",
      "org.joo.libra.text.ContainPredicate",
      "org.joo.libra.text.MatchPredicate",
      "org.joo.libra.numeric.GreaterPredicate",
      "org.joo.libra.numeric.LessPredicate",
      "org.joo.libra.common.HasValue",
      "org.joo.libra.support.MalformedSyntaxException",
      "org.joo.libra.logic.NotPredicate",
      "org.joo.libra.text.IsEmptyPredicate",
      "org.joo.libra.logic.AndPredicate",
      "org.joo.libra.numeric.NumericComparator",
      "org.joo.libra.logic.OrPredicate",
      "org.joo.libra.text.EqualsIgnoreCase",
      "org.joo.libra.sql.SqlPredicate",
      "org.joo.libra.common.CompositionPredicate",
      "org.joo.libra.common.SimplePredicate",
      "org.joo.libra.Predicate",
      "org.joo.libra.sql.SqlPredicateParser",
      "org.joo.libra.pointer.VariablePredicate",
      "org.joo.libra.pointer.IsNullPredicate"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(VariablePredicate_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.joo.libra.pointer.VariablePredicate",
      "org.joo.libra.common.SimpleHasValue",
      "org.joo.libra.PredicateContext",
      "org.joo.libra.common.BinaryPredicate",
      "org.joo.libra.text.EqualsIgnoreCase",
      "org.joo.libra.logic.OrPredicate",
      "org.joo.libra.logic.EqualsPredicate",
      "org.joo.libra.logic.AndPredicate",
      "org.joo.libra.text.MatchPredicate",
      "org.joo.libra.numeric.LessEqualPredicate",
      "org.joo.libra.logic.NotPredicate",
      "org.joo.libra.pointer.IsNullPredicate",
      "org.joo.libra.common.SimplePredicate",
      "org.joo.libra.sql.SqlPredicate",
      "org.joo.libra.text.IsEmptyPredicate",
      "org.joo.libra.support.MalformedSyntaxException",
      "org.joo.libra.text.ContainPredicate",
      "org.joo.libra.numeric.LessPredicate",
      "org.joo.libra.numeric.GreaterEqualPredicate",
      "org.joo.libra.numeric.GreaterPredicate",
      "org.joo.libra.numeric.NumericComparator"
    );
  }
}
