/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 09 22:40:50 GMT 2019
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.traccar.protocol.Gt06Protocol;
import org.traccar.protocol.Gt06ProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Gt06ProtocolDecoder_ESTest extends Gt06ProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Gt06Protocol gt06Protocol0 = new Gt06Protocol();
      Gt06ProtocolDecoder gt06ProtocolDecoder0 = null;
      try {
        gt06ProtocolDecoder0 = new Gt06ProtocolDecoder(gt06Protocol0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.Gt06ProtocolDecoder", e);
      }
  }
}
